### ISSUE TITLE
Geolokalizacja

### ISSUE THREAD

**Issue by KageYoshi777** [pixinixi/otodom_scraper#3]
Hej, chciałem przetestować skrypt w celu uzyskania geolokalizacji, prawdopodobnie już nie działa.. W ogólnie nie ma pobiera informacji o szerokosci czy wysokosci geograficznej
Przewidujesz jakieś kolejne iteracje scrapera albo masz może już to jakoś naprawione?

**Comment by pixinixi** [comment]
Nie widzę już informacji o koordynatach u nich na stronie. Można wydobyć adres i po nim dodać info o geolokacji. Ja raczej nie znajdę na to czasu.
